### PR TITLE
Update sys.config.turbo

### PR DESCRIPTION
**Pull request by moophlo**

### CODE REVIEW

**Comment by inigoflores** [comment]
Thanks for this. I believe it's for the typo (excess comma) which I fixed and committed a few minutes before your pull request. Please confirm.

**Comment by moophlo** [comment]
I saw your comment on the last commit about the typo and i understand it was the last comma before the closing, but I've tried also the new version and it seemed to me it was still giving error, but it can also dued to github raw file taking a bit to update

**Comment by moophlo** [comment]
tried again now, with your version at first start it gives a Broken pipe and dumped, then restarted fine, strange

**Comment by inigoflores** [comment]
Yes, I think the raw version takes some time to update. I've just tested the patch on three miners, and it seems to work. Please let me know otherwise. Thanks.

**Comment by GGAlanSmithee** [comment]
Yes, the GitHub CDN takes some time to refresh

**Comment by moophlo** [comment]
I can confirm it works perfectly

**Pull request closed without merging**
